language: rust
rust:
  - stable
#  - beta
#  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
